### ISSUE TITLE
Make some nice plots of voltage traces

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#7]
For example: a) silence at I=-5, b) silence or spiking depending on previous state at I=-2.2, c) large spikes at I=0, d) small spikes at I=40, e) oscillations without spikes at I=65

**Comment by borismarin** [comment]
pulse-induced transitions (silence->firing / firing->silence) for bistable cases

**Comment by jrieke** [comment]
![voltage_traces](https://cloud.githubusercontent.com/assets/5103165/11105386/cf08c3d0-88ce-11e5-8ea5-08fd3081a054.png)

A: Silent behaviour at low currents. In response to a short square current pulse, a single spike is emitted.
B: Bistable behaviour. The system can be switched from silent to spiking behaviour (and back) via short square current pulses.
C: Tonic spiking.
D: Silent behaviour and oscillations at high currents.

**Comment by jrieke** [comment]
Btw, I want to use the letters A-D throughout the thesis to divide the behaviour into its four qualitatively different regions:

![image](https://cloud.githubusercontent.com/assets/5103165/11105591/302b92d6-88d0-11e5-8a63-dbfd1febbe4c.png)

**Comment by borismarin** [comment]
Good looking plots!

some random comments:
- make it clear that there is always a baseline dc bias (explain the two
  current steps in A,B)
- B: would it be possible to show more spikes (you might have to change the
  timescale or the dc bias)?
- D: sometimes called "depolarization block", can you get it via modulating
  gleak instead of high currents?
- explain the effect of short pulses vs permanent bias. In other words,
  describe what happens (in terms of the dynamics) in B as you apply the
  pulses.

**Comment by jrieke** [comment]
I tweaked B to show three spikes - still not that much but otherwise the features in the other plots become really hard to distinguish (considering the space I have on a page) or it looks like B would spike right from the beginning.
![image](https://cloud.githubusercontent.com/assets/5103165/11133560/b6cfd8f8-8996-11e5-9e2e-92e7b6c71317.png)
I think this plot should at least make it clear that it's tonic spiking.
